//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public long Bookingid { get; set; }
        public string Guestid { get; set; }
        public string Roomid { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public System.DateTime Checkindate { get; set; }
        public Nullable<System.DateTime> Checkoutdate { get; set; }
        public Nullable<long> Status { get; set; }
    }
}
