//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public long BookingID { get; set; }
        public Nullable<long> GuestId { get; set; }
        public Nullable<long> RoomId { get; set; }
        public Nullable<System.DateTime> CheckinDate { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public long StatusId { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual Room Room { get; set; }
        public virtual Status Status { get; set; }
    }
}
